#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingHotel.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BOOKING_HOTEL")]
	public partial class DataBookingHotelDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertChinhSach(ChinhSach instance);
    partial void UpdateChinhSach(ChinhSach instance);
    partial void DeleteChinhSach(ChinhSach instance);
    partial void InsertTienIch(TienIch instance);
    partial void UpdateTienIch(TienIch instance);
    partial void DeleteTienIch(TienIch instance);
    partial void InsertChiTiet_DonDatPhong(ChiTiet_DonDatPhong instance);
    partial void UpdateChiTiet_DonDatPhong(ChiTiet_DonDatPhong instance);
    partial void DeleteChiTiet_DonDatPhong(ChiTiet_DonDatPhong instance);
    partial void InsertChiTiet_LoaiPhong(ChiTiet_LoaiPhong instance);
    partial void UpdateChiTiet_LoaiPhong(ChiTiet_LoaiPhong instance);
    partial void DeleteChiTiet_LoaiPhong(ChiTiet_LoaiPhong instance);
    partial void InsertCT_DichVu(CT_DichVu instance);
    partial void UpdateCT_DichVu(CT_DichVu instance);
    partial void DeleteCT_DichVu(CT_DichVu instance);
    partial void InsertCT_TienIch(CT_TienIch instance);
    partial void UpdateCT_TienIch(CT_TienIch instance);
    partial void DeleteCT_TienIch(CT_TienIch instance);
    partial void InsertDanhGia(DanhGia instance);
    partial void UpdateDanhGia(DanhGia instance);
    partial void DeleteDanhGia(DanhGia instance);
    partial void InsertDiaDiem(DiaDiem instance);
    partial void UpdateDiaDiem(DiaDiem instance);
    partial void DeleteDiaDiem(DiaDiem instance);
    partial void InsertDichVu(DichVu instance);
    partial void UpdateDichVu(DichVu instance);
    partial void DeleteDichVu(DichVu instance);
    partial void InsertDonDatPhong(DonDatPhong instance);
    partial void UpdateDonDatPhong(DonDatPhong instance);
    partial void DeleteDonDatPhong(DonDatPhong instance);
    partial void InsertHinhAnh(HinhAnh instance);
    partial void UpdateHinhAnh(HinhAnh instance);
    partial void DeleteHinhAnh(HinhAnh instance);
    partial void InsertKhachHang(KhachHang instance);
    partial void UpdateKhachHang(KhachHang instance);
    partial void DeleteKhachHang(KhachHang instance);
    partial void InsertKhachSan(KhachSan instance);
    partial void UpdateKhachSan(KhachSan instance);
    partial void DeleteKhachSan(KhachSan instance);
    partial void InsertLienHe(LienHe instance);
    partial void UpdateLienHe(LienHe instance);
    partial void DeleteLienHe(LienHe instance);
    partial void InsertLoaiPhong(LoaiPhong instance);
    partial void UpdateLoaiPhong(LoaiPhong instance);
    partial void DeleteLoaiPhong(LoaiPhong instance);
    partial void InsertQuanTri(QuanTri instance);
    partial void UpdateQuanTri(QuanTri instance);
    partial void DeleteQuanTri(QuanTri instance);
    partial void InsertQuyenHan(QuyenHan instance);
    partial void UpdateQuyenHan(QuyenHan instance);
    partial void DeleteQuyenHan(QuyenHan instance);
    #endregion
		
		public DataBookingHotelDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["BOOKING_HOTELConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataBookingHotelDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataBookingHotelDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataBookingHotelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataBookingHotelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ChinhSach> ChinhSaches
		{
			get
			{
				return this.GetTable<ChinhSach>();
			}
		}
		
		public System.Data.Linq.Table<TienIch> TienIches
		{
			get
			{
				return this.GetTable<TienIch>();
			}
		}
		
		public System.Data.Linq.Table<ChiTiet_DonDatPhong> ChiTiet_DonDatPhongs
		{
			get
			{
				return this.GetTable<ChiTiet_DonDatPhong>();
			}
		}
		
		public System.Data.Linq.Table<ChiTiet_LoaiPhong> ChiTiet_LoaiPhongs
		{
			get
			{
				return this.GetTable<ChiTiet_LoaiPhong>();
			}
		}
		
		public System.Data.Linq.Table<CT_DichVu> CT_DichVus
		{
			get
			{
				return this.GetTable<CT_DichVu>();
			}
		}
		
		public System.Data.Linq.Table<CT_TienIch> CT_TienIches
		{
			get
			{
				return this.GetTable<CT_TienIch>();
			}
		}
		
		public System.Data.Linq.Table<DanhGia> DanhGias
		{
			get
			{
				return this.GetTable<DanhGia>();
			}
		}
		
		public System.Data.Linq.Table<DiaDiem> DiaDiems
		{
			get
			{
				return this.GetTable<DiaDiem>();
			}
		}
		
		public System.Data.Linq.Table<DichVu> DichVus
		{
			get
			{
				return this.GetTable<DichVu>();
			}
		}
		
		public System.Data.Linq.Table<DonDatPhong> DonDatPhongs
		{
			get
			{
				return this.GetTable<DonDatPhong>();
			}
		}
		
		public System.Data.Linq.Table<HinhAnh> HinhAnhs
		{
			get
			{
				return this.GetTable<HinhAnh>();
			}
		}
		
		public System.Data.Linq.Table<KhachHang> KhachHangs
		{
			get
			{
				return this.GetTable<KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<KhachSan> KhachSans
		{
			get
			{
				return this.GetTable<KhachSan>();
			}
		}
		
		public System.Data.Linq.Table<LienHe> LienHes
		{
			get
			{
				return this.GetTable<LienHe>();
			}
		}
		
		public System.Data.Linq.Table<LoaiPhong> LoaiPhongs
		{
			get
			{
				return this.GetTable<LoaiPhong>();
			}
		}
		
		public System.Data.Linq.Table<QuanTri> QuanTris
		{
			get
			{
				return this.GetTable<QuanTri>();
			}
		}
		
		public System.Data.Linq.Table<QuyenHan> QuyenHans
		{
			get
			{
				return this.GetTable<QuyenHan>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChinhSach")]
	public partial class ChinhSach : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaChinhSach;
		
		private System.Nullable<int> _MaKhachSan;
		
		private string _ThoiGianNhanPhong;
		
		private string _ThoiGianTraPhong;
		
		private string _HuongDan;
		
		private string _ChinhSachNhanTra;
		
		private string _ChinhSachTreEm;
		
		private string _BaiDauXe;
		
		private EntityRef<KhachSan> _KhachSan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaChinhSachChanging(int value);
    partial void OnMaChinhSachChanged();
    partial void OnMaKhachSanChanging(System.Nullable<int> value);
    partial void OnMaKhachSanChanged();
    partial void OnThoiGianNhanPhongChanging(string value);
    partial void OnThoiGianNhanPhongChanged();
    partial void OnThoiGianTraPhongChanging(string value);
    partial void OnThoiGianTraPhongChanged();
    partial void OnHuongDanChanging(string value);
    partial void OnHuongDanChanged();
    partial void OnChinhSachNhanTraChanging(string value);
    partial void OnChinhSachNhanTraChanged();
    partial void OnChinhSachTreEmChanging(string value);
    partial void OnChinhSachTreEmChanged();
    partial void OnBaiDauXeChanging(string value);
    partial void OnBaiDauXeChanged();
    #endregion
		
		public ChinhSach()
		{
			this._KhachSan = default(EntityRef<KhachSan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChinhSach", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaChinhSach
		{
			get
			{
				return this._MaChinhSach;
			}
			set
			{
				if ((this._MaChinhSach != value))
				{
					this.OnMaChinhSachChanging(value);
					this.SendPropertyChanging();
					this._MaChinhSach = value;
					this.SendPropertyChanged("MaChinhSach");
					this.OnMaChinhSachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhachSan", DbType="Int")]
		public System.Nullable<int> MaKhachSan
		{
			get
			{
				return this._MaKhachSan;
			}
			set
			{
				if ((this._MaKhachSan != value))
				{
					if (this._KhachSan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhachSanChanging(value);
					this.SendPropertyChanging();
					this._MaKhachSan = value;
					this.SendPropertyChanged("MaKhachSan");
					this.OnMaKhachSanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianNhanPhong", DbType="VarChar(5)")]
		public string ThoiGianNhanPhong
		{
			get
			{
				return this._ThoiGianNhanPhong;
			}
			set
			{
				if ((this._ThoiGianNhanPhong != value))
				{
					this.OnThoiGianNhanPhongChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianNhanPhong = value;
					this.SendPropertyChanged("ThoiGianNhanPhong");
					this.OnThoiGianNhanPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianTraPhong", DbType="VarChar(5)")]
		public string ThoiGianTraPhong
		{
			get
			{
				return this._ThoiGianTraPhong;
			}
			set
			{
				if ((this._ThoiGianTraPhong != value))
				{
					this.OnThoiGianTraPhongChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianTraPhong = value;
					this.SendPropertyChanged("ThoiGianTraPhong");
					this.OnThoiGianTraPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HuongDan", DbType="NVarChar(100)")]
		public string HuongDan
		{
			get
			{
				return this._HuongDan;
			}
			set
			{
				if ((this._HuongDan != value))
				{
					this.OnHuongDanChanging(value);
					this.SendPropertyChanging();
					this._HuongDan = value;
					this.SendPropertyChanged("HuongDan");
					this.OnHuongDanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChinhSachNhanTra", DbType="NVarChar(500)")]
		public string ChinhSachNhanTra
		{
			get
			{
				return this._ChinhSachNhanTra;
			}
			set
			{
				if ((this._ChinhSachNhanTra != value))
				{
					this.OnChinhSachNhanTraChanging(value);
					this.SendPropertyChanging();
					this._ChinhSachNhanTra = value;
					this.SendPropertyChanged("ChinhSachNhanTra");
					this.OnChinhSachNhanTraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChinhSachTreEm", DbType="NVarChar(500)")]
		public string ChinhSachTreEm
		{
			get
			{
				return this._ChinhSachTreEm;
			}
			set
			{
				if ((this._ChinhSachTreEm != value))
				{
					this.OnChinhSachTreEmChanging(value);
					this.SendPropertyChanging();
					this._ChinhSachTreEm = value;
					this.SendPropertyChanged("ChinhSachTreEm");
					this.OnChinhSachTreEmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaiDauXe", DbType="NVarChar(50)")]
		public string BaiDauXe
		{
			get
			{
				return this._BaiDauXe;
			}
			set
			{
				if ((this._BaiDauXe != value))
				{
					this.OnBaiDauXeChanging(value);
					this.SendPropertyChanging();
					this._BaiDauXe = value;
					this.SendPropertyChanged("BaiDauXe");
					this.OnBaiDauXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachSan_ChinhSach", Storage="_KhachSan", ThisKey="MaKhachSan", OtherKey="MaKhachSan", IsForeignKey=true)]
		public KhachSan KhachSan
		{
			get
			{
				return this._KhachSan.Entity;
			}
			set
			{
				KhachSan previousValue = this._KhachSan.Entity;
				if (((previousValue != value) 
							|| (this._KhachSan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachSan.Entity = null;
						previousValue.ChinhSaches.Remove(this);
					}
					this._KhachSan.Entity = value;
					if ((value != null))
					{
						value.ChinhSaches.Add(this);
						this._MaKhachSan = value.MaKhachSan;
					}
					else
					{
						this._MaKhachSan = default(Nullable<int>);
					}
					this.SendPropertyChanged("KhachSan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TienIch")]
	public partial class TienIch : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaTienIch;
		
		private string _TenTienIch;
		
		private string _ThongTin;
		
		private EntitySet<CT_TienIch> _CT_TienIches;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTienIchChanging(int value);
    partial void OnMaTienIchChanged();
    partial void OnTenTienIchChanging(string value);
    partial void OnTenTienIchChanged();
    partial void OnThongTinChanging(string value);
    partial void OnThongTinChanged();
    #endregion
		
		public TienIch()
		{
			this._CT_TienIches = new EntitySet<CT_TienIch>(new Action<CT_TienIch>(this.attach_CT_TienIches), new Action<CT_TienIch>(this.detach_CT_TienIches));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTienIch", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaTienIch
		{
			get
			{
				return this._MaTienIch;
			}
			set
			{
				if ((this._MaTienIch != value))
				{
					this.OnMaTienIchChanging(value);
					this.SendPropertyChanging();
					this._MaTienIch = value;
					this.SendPropertyChanged("MaTienIch");
					this.OnMaTienIchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTienIch", DbType="NVarChar(50)")]
		public string TenTienIch
		{
			get
			{
				return this._TenTienIch;
			}
			set
			{
				if ((this._TenTienIch != value))
				{
					this.OnTenTienIchChanging(value);
					this.SendPropertyChanging();
					this._TenTienIch = value;
					this.SendPropertyChanged("TenTienIch");
					this.OnTenTienIchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThongTin", DbType="NVarChar(100)")]
		public string ThongTin
		{
			get
			{
				return this._ThongTin;
			}
			set
			{
				if ((this._ThongTin != value))
				{
					this.OnThongTinChanging(value);
					this.SendPropertyChanging();
					this._ThongTin = value;
					this.SendPropertyChanged("ThongTin");
					this.OnThongTinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TienIch_CT_TienIch", Storage="_CT_TienIches", ThisKey="MaTienIch", OtherKey="MaTienIch")]
		public EntitySet<CT_TienIch> CT_TienIches
		{
			get
			{
				return this._CT_TienIches;
			}
			set
			{
				this._CT_TienIches.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CT_TienIches(CT_TienIch entity)
		{
			this.SendPropertyChanging();
			entity.TienIch = this;
		}
		
		private void detach_CT_TienIches(CT_TienIch entity)
		{
			this.SendPropertyChanging();
			entity.TienIch = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTiet_DonDatPhong")]
	public partial class ChiTiet_DonDatPhong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDonDatPhong;
		
		private int _MaChiTietLoaiPhong;
		
		private System.Nullable<int> _SoPhong;
		
		private System.Nullable<decimal> _ThanhTien;
		
		private EntityRef<ChiTiet_LoaiPhong> _ChiTiet_LoaiPhong;
		
		private EntityRef<DonDatPhong> _DonDatPhong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDonDatPhongChanging(int value);
    partial void OnMaDonDatPhongChanged();
    partial void OnMaChiTietLoaiPhongChanging(int value);
    partial void OnMaChiTietLoaiPhongChanged();
    partial void OnSoPhongChanging(System.Nullable<int> value);
    partial void OnSoPhongChanged();
    partial void OnThanhTienChanging(System.Nullable<decimal> value);
    partial void OnThanhTienChanged();
    #endregion
		
		public ChiTiet_DonDatPhong()
		{
			this._ChiTiet_LoaiPhong = default(EntityRef<ChiTiet_LoaiPhong>);
			this._DonDatPhong = default(EntityRef<DonDatPhong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDonDatPhong", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaDonDatPhong
		{
			get
			{
				return this._MaDonDatPhong;
			}
			set
			{
				if ((this._MaDonDatPhong != value))
				{
					if (this._DonDatPhong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDonDatPhongChanging(value);
					this.SendPropertyChanging();
					this._MaDonDatPhong = value;
					this.SendPropertyChanged("MaDonDatPhong");
					this.OnMaDonDatPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChiTietLoaiPhong", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaChiTietLoaiPhong
		{
			get
			{
				return this._MaChiTietLoaiPhong;
			}
			set
			{
				if ((this._MaChiTietLoaiPhong != value))
				{
					if (this._ChiTiet_LoaiPhong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaChiTietLoaiPhongChanging(value);
					this.SendPropertyChanging();
					this._MaChiTietLoaiPhong = value;
					this.SendPropertyChanged("MaChiTietLoaiPhong");
					this.OnMaChiTietLoaiPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoPhong", DbType="Int")]
		public System.Nullable<int> SoPhong
		{
			get
			{
				return this._SoPhong;
			}
			set
			{
				if ((this._SoPhong != value))
				{
					this.OnSoPhongChanging(value);
					this.SendPropertyChanging();
					this._SoPhong = value;
					this.SendPropertyChanged("SoPhong");
					this.OnSoPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanhTien", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> ThanhTien
		{
			get
			{
				return this._ThanhTien;
			}
			set
			{
				if ((this._ThanhTien != value))
				{
					this.OnThanhTienChanging(value);
					this.SendPropertyChanging();
					this._ThanhTien = value;
					this.SendPropertyChanged("ThanhTien");
					this.OnThanhTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChiTiet_LoaiPhong_ChiTiet_DonDatPhong", Storage="_ChiTiet_LoaiPhong", ThisKey="MaChiTietLoaiPhong", OtherKey="MaChiTietLoaiPhong", IsForeignKey=true)]
		public ChiTiet_LoaiPhong ChiTiet_LoaiPhong
		{
			get
			{
				return this._ChiTiet_LoaiPhong.Entity;
			}
			set
			{
				ChiTiet_LoaiPhong previousValue = this._ChiTiet_LoaiPhong.Entity;
				if (((previousValue != value) 
							|| (this._ChiTiet_LoaiPhong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ChiTiet_LoaiPhong.Entity = null;
						previousValue.ChiTiet_DonDatPhongs.Remove(this);
					}
					this._ChiTiet_LoaiPhong.Entity = value;
					if ((value != null))
					{
						value.ChiTiet_DonDatPhongs.Add(this);
						this._MaChiTietLoaiPhong = value.MaChiTietLoaiPhong;
					}
					else
					{
						this._MaChiTietLoaiPhong = default(int);
					}
					this.SendPropertyChanged("ChiTiet_LoaiPhong");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DonDatPhong_ChiTiet_DonDatPhong", Storage="_DonDatPhong", ThisKey="MaDonDatPhong", OtherKey="MaDonDatPhong", IsForeignKey=true)]
		public DonDatPhong DonDatPhong
		{
			get
			{
				return this._DonDatPhong.Entity;
			}
			set
			{
				DonDatPhong previousValue = this._DonDatPhong.Entity;
				if (((previousValue != value) 
							|| (this._DonDatPhong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DonDatPhong.Entity = null;
						previousValue.ChiTiet_DonDatPhongs.Remove(this);
					}
					this._DonDatPhong.Entity = value;
					if ((value != null))
					{
						value.ChiTiet_DonDatPhongs.Add(this);
						this._MaDonDatPhong = value.MaDonDatPhong;
					}
					else
					{
						this._MaDonDatPhong = default(int);
					}
					this.SendPropertyChanged("DonDatPhong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTiet_LoaiPhong")]
	public partial class ChiTiet_LoaiPhong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaChiTietLoaiPhong;
		
		private int _MaKhachSan;
		
		private int _MaLoaiPhong;
		
		private System.Nullable<decimal> _GiaPhong;
		
		private System.Nullable<int> _SoLuongToiDa;
		
		private string _HinhAnh;
		
		private System.Nullable<int> _SoLuongPhong;
		
		private string _KhuyenMai;
		
		private EntitySet<ChiTiet_DonDatPhong> _ChiTiet_DonDatPhongs;
		
		private EntityRef<KhachSan> _KhachSan;
		
		private EntityRef<LoaiPhong> _LoaiPhong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaChiTietLoaiPhongChanging(int value);
    partial void OnMaChiTietLoaiPhongChanged();
    partial void OnMaKhachSanChanging(int value);
    partial void OnMaKhachSanChanged();
    partial void OnMaLoaiPhongChanging(int value);
    partial void OnMaLoaiPhongChanged();
    partial void OnGiaPhongChanging(System.Nullable<decimal> value);
    partial void OnGiaPhongChanged();
    partial void OnSoLuongToiDaChanging(System.Nullable<int> value);
    partial void OnSoLuongToiDaChanged();
    partial void OnHinhAnhChanging(string value);
    partial void OnHinhAnhChanged();
    partial void OnSoLuongPhongChanging(System.Nullable<int> value);
    partial void OnSoLuongPhongChanged();
    partial void OnKhuyenMaiChanging(string value);
    partial void OnKhuyenMaiChanged();
    #endregion
		
		public ChiTiet_LoaiPhong()
		{
			this._ChiTiet_DonDatPhongs = new EntitySet<ChiTiet_DonDatPhong>(new Action<ChiTiet_DonDatPhong>(this.attach_ChiTiet_DonDatPhongs), new Action<ChiTiet_DonDatPhong>(this.detach_ChiTiet_DonDatPhongs));
			this._KhachSan = default(EntityRef<KhachSan>);
			this._LoaiPhong = default(EntityRef<LoaiPhong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChiTietLoaiPhong", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaChiTietLoaiPhong
		{
			get
			{
				return this._MaChiTietLoaiPhong;
			}
			set
			{
				if ((this._MaChiTietLoaiPhong != value))
				{
					this.OnMaChiTietLoaiPhongChanging(value);
					this.SendPropertyChanging();
					this._MaChiTietLoaiPhong = value;
					this.SendPropertyChanged("MaChiTietLoaiPhong");
					this.OnMaChiTietLoaiPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhachSan", DbType="Int NOT NULL")]
		public int MaKhachSan
		{
			get
			{
				return this._MaKhachSan;
			}
			set
			{
				if ((this._MaKhachSan != value))
				{
					if (this._KhachSan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhachSanChanging(value);
					this.SendPropertyChanging();
					this._MaKhachSan = value;
					this.SendPropertyChanged("MaKhachSan");
					this.OnMaKhachSanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiPhong", DbType="Int NOT NULL")]
		public int MaLoaiPhong
		{
			get
			{
				return this._MaLoaiPhong;
			}
			set
			{
				if ((this._MaLoaiPhong != value))
				{
					if (this._LoaiPhong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoaiPhongChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiPhong = value;
					this.SendPropertyChanged("MaLoaiPhong");
					this.OnMaLoaiPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaPhong", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> GiaPhong
		{
			get
			{
				return this._GiaPhong;
			}
			set
			{
				if ((this._GiaPhong != value))
				{
					this.OnGiaPhongChanging(value);
					this.SendPropertyChanging();
					this._GiaPhong = value;
					this.SendPropertyChanged("GiaPhong");
					this.OnGiaPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongToiDa", DbType="Int")]
		public System.Nullable<int> SoLuongToiDa
		{
			get
			{
				return this._SoLuongToiDa;
			}
			set
			{
				if ((this._SoLuongToiDa != value))
				{
					this.OnSoLuongToiDaChanging(value);
					this.SendPropertyChanging();
					this._SoLuongToiDa = value;
					this.SendPropertyChanged("SoLuongToiDa");
					this.OnSoLuongToiDaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh", DbType="VarChar(50)")]
		public string HinhAnh
		{
			get
			{
				return this._HinhAnh;
			}
			set
			{
				if ((this._HinhAnh != value))
				{
					this.OnHinhAnhChanging(value);
					this.SendPropertyChanging();
					this._HinhAnh = value;
					this.SendPropertyChanged("HinhAnh");
					this.OnHinhAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongPhong", DbType="Int")]
		public System.Nullable<int> SoLuongPhong
		{
			get
			{
				return this._SoLuongPhong;
			}
			set
			{
				if ((this._SoLuongPhong != value))
				{
					this.OnSoLuongPhongChanging(value);
					this.SendPropertyChanging();
					this._SoLuongPhong = value;
					this.SendPropertyChanged("SoLuongPhong");
					this.OnSoLuongPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhuyenMai", DbType="NVarChar(50)")]
		public string KhuyenMai
		{
			get
			{
				return this._KhuyenMai;
			}
			set
			{
				if ((this._KhuyenMai != value))
				{
					this.OnKhuyenMaiChanging(value);
					this.SendPropertyChanging();
					this._KhuyenMai = value;
					this.SendPropertyChanged("KhuyenMai");
					this.OnKhuyenMaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChiTiet_LoaiPhong_ChiTiet_DonDatPhong", Storage="_ChiTiet_DonDatPhongs", ThisKey="MaChiTietLoaiPhong", OtherKey="MaChiTietLoaiPhong")]
		public EntitySet<ChiTiet_DonDatPhong> ChiTiet_DonDatPhongs
		{
			get
			{
				return this._ChiTiet_DonDatPhongs;
			}
			set
			{
				this._ChiTiet_DonDatPhongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachSan_ChiTiet_LoaiPhong", Storage="_KhachSan", ThisKey="MaKhachSan", OtherKey="MaKhachSan", IsForeignKey=true)]
		public KhachSan KhachSan
		{
			get
			{
				return this._KhachSan.Entity;
			}
			set
			{
				KhachSan previousValue = this._KhachSan.Entity;
				if (((previousValue != value) 
							|| (this._KhachSan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachSan.Entity = null;
						previousValue.ChiTiet_LoaiPhongs.Remove(this);
					}
					this._KhachSan.Entity = value;
					if ((value != null))
					{
						value.ChiTiet_LoaiPhongs.Add(this);
						this._MaKhachSan = value.MaKhachSan;
					}
					else
					{
						this._MaKhachSan = default(int);
					}
					this.SendPropertyChanged("KhachSan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiPhong_ChiTiet_LoaiPhong", Storage="_LoaiPhong", ThisKey="MaLoaiPhong", OtherKey="MaLoaiPhong", IsForeignKey=true)]
		public LoaiPhong LoaiPhong
		{
			get
			{
				return this._LoaiPhong.Entity;
			}
			set
			{
				LoaiPhong previousValue = this._LoaiPhong.Entity;
				if (((previousValue != value) 
							|| (this._LoaiPhong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiPhong.Entity = null;
						previousValue.ChiTiet_LoaiPhongs.Remove(this);
					}
					this._LoaiPhong.Entity = value;
					if ((value != null))
					{
						value.ChiTiet_LoaiPhongs.Add(this);
						this._MaLoaiPhong = value.MaLoaiPhong;
					}
					else
					{
						this._MaLoaiPhong = default(int);
					}
					this.SendPropertyChanged("LoaiPhong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTiet_DonDatPhongs(ChiTiet_DonDatPhong entity)
		{
			this.SendPropertyChanging();
			entity.ChiTiet_LoaiPhong = this;
		}
		
		private void detach_ChiTiet_DonDatPhongs(ChiTiet_DonDatPhong entity)
		{
			this.SendPropertyChanging();
			entity.ChiTiet_LoaiPhong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CT_DichVu")]
	public partial class CT_DichVu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaKhachSan;
		
		private int _MaDichVu;
		
		private System.Nullable<decimal> _DonGia;
		
		private EntityRef<DichVu> _DichVu;
		
		private EntityRef<KhachSan> _KhachSan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKhachSanChanging(int value);
    partial void OnMaKhachSanChanged();
    partial void OnMaDichVuChanging(int value);
    partial void OnMaDichVuChanged();
    partial void OnDonGiaChanging(System.Nullable<decimal> value);
    partial void OnDonGiaChanged();
    #endregion
		
		public CT_DichVu()
		{
			this._DichVu = default(EntityRef<DichVu>);
			this._KhachSan = default(EntityRef<KhachSan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhachSan", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaKhachSan
		{
			get
			{
				return this._MaKhachSan;
			}
			set
			{
				if ((this._MaKhachSan != value))
				{
					if (this._KhachSan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhachSanChanging(value);
					this.SendPropertyChanging();
					this._MaKhachSan = value;
					this.SendPropertyChanged("MaKhachSan");
					this.OnMaKhachSanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDichVu", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaDichVu
		{
			get
			{
				return this._MaDichVu;
			}
			set
			{
				if ((this._MaDichVu != value))
				{
					if (this._DichVu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDichVuChanging(value);
					this.SendPropertyChanging();
					this._MaDichVu = value;
					this.SendPropertyChanged("MaDichVu");
					this.OnMaDichVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this.OnDonGiaChanging(value);
					this.SendPropertyChanging();
					this._DonGia = value;
					this.SendPropertyChanged("DonGia");
					this.OnDonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DichVu_CT_DichVu", Storage="_DichVu", ThisKey="MaDichVu", OtherKey="MaDichVu", IsForeignKey=true)]
		public DichVu DichVu
		{
			get
			{
				return this._DichVu.Entity;
			}
			set
			{
				DichVu previousValue = this._DichVu.Entity;
				if (((previousValue != value) 
							|| (this._DichVu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DichVu.Entity = null;
						previousValue.CT_DichVus.Remove(this);
					}
					this._DichVu.Entity = value;
					if ((value != null))
					{
						value.CT_DichVus.Add(this);
						this._MaDichVu = value.MaDichVu;
					}
					else
					{
						this._MaDichVu = default(int);
					}
					this.SendPropertyChanged("DichVu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachSan_CT_DichVu", Storage="_KhachSan", ThisKey="MaKhachSan", OtherKey="MaKhachSan", IsForeignKey=true)]
		public KhachSan KhachSan
		{
			get
			{
				return this._KhachSan.Entity;
			}
			set
			{
				KhachSan previousValue = this._KhachSan.Entity;
				if (((previousValue != value) 
							|| (this._KhachSan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachSan.Entity = null;
						previousValue.CT_DichVus.Remove(this);
					}
					this._KhachSan.Entity = value;
					if ((value != null))
					{
						value.CT_DichVus.Add(this);
						this._MaKhachSan = value.MaKhachSan;
					}
					else
					{
						this._MaKhachSan = default(int);
					}
					this.SendPropertyChanged("KhachSan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CT_TienIch")]
	public partial class CT_TienIch : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaKhachSan;
		
		private int _MaTienIch;
		
		private System.Nullable<decimal> _DonGia;
		
		private EntityRef<TienIch> _TienIch;
		
		private EntityRef<KhachSan> _KhachSan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKhachSanChanging(int value);
    partial void OnMaKhachSanChanged();
    partial void OnMaTienIchChanging(int value);
    partial void OnMaTienIchChanged();
    partial void OnDonGiaChanging(System.Nullable<decimal> value);
    partial void OnDonGiaChanged();
    #endregion
		
		public CT_TienIch()
		{
			this._TienIch = default(EntityRef<TienIch>);
			this._KhachSan = default(EntityRef<KhachSan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhachSan", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaKhachSan
		{
			get
			{
				return this._MaKhachSan;
			}
			set
			{
				if ((this._MaKhachSan != value))
				{
					if (this._KhachSan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhachSanChanging(value);
					this.SendPropertyChanging();
					this._MaKhachSan = value;
					this.SendPropertyChanged("MaKhachSan");
					this.OnMaKhachSanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTienIch", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaTienIch
		{
			get
			{
				return this._MaTienIch;
			}
			set
			{
				if ((this._MaTienIch != value))
				{
					if (this._TienIch.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTienIchChanging(value);
					this.SendPropertyChanging();
					this._MaTienIch = value;
					this.SendPropertyChanged("MaTienIch");
					this.OnMaTienIchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this.OnDonGiaChanging(value);
					this.SendPropertyChanging();
					this._DonGia = value;
					this.SendPropertyChanged("DonGia");
					this.OnDonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TienIch_CT_TienIch", Storage="_TienIch", ThisKey="MaTienIch", OtherKey="MaTienIch", IsForeignKey=true)]
		public TienIch TienIch
		{
			get
			{
				return this._TienIch.Entity;
			}
			set
			{
				TienIch previousValue = this._TienIch.Entity;
				if (((previousValue != value) 
							|| (this._TienIch.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TienIch.Entity = null;
						previousValue.CT_TienIches.Remove(this);
					}
					this._TienIch.Entity = value;
					if ((value != null))
					{
						value.CT_TienIches.Add(this);
						this._MaTienIch = value.MaTienIch;
					}
					else
					{
						this._MaTienIch = default(int);
					}
					this.SendPropertyChanged("TienIch");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachSan_CT_TienIch", Storage="_KhachSan", ThisKey="MaKhachSan", OtherKey="MaKhachSan", IsForeignKey=true)]
		public KhachSan KhachSan
		{
			get
			{
				return this._KhachSan.Entity;
			}
			set
			{
				KhachSan previousValue = this._KhachSan.Entity;
				if (((previousValue != value) 
							|| (this._KhachSan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachSan.Entity = null;
						previousValue.CT_TienIches.Remove(this);
					}
					this._KhachSan.Entity = value;
					if ((value != null))
					{
						value.CT_TienIches.Add(this);
						this._MaKhachSan = value.MaKhachSan;
					}
					else
					{
						this._MaKhachSan = default(int);
					}
					this.SendPropertyChanged("KhachSan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DanhGia")]
	public partial class DanhGia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDanhGia;
		
		private System.Nullable<decimal> _DiemDanhGia;
		
		private string _ThuocLoai;
		
		private System.Nullable<int> _MaKhachSan;
		
		private EntityRef<KhachSan> _KhachSan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDanhGiaChanging(int value);
    partial void OnMaDanhGiaChanged();
    partial void OnDiemDanhGiaChanging(System.Nullable<decimal> value);
    partial void OnDiemDanhGiaChanged();
    partial void OnThuocLoaiChanging(string value);
    partial void OnThuocLoaiChanged();
    partial void OnMaKhachSanChanging(System.Nullable<int> value);
    partial void OnMaKhachSanChanged();
    #endregion
		
		public DanhGia()
		{
			this._KhachSan = default(EntityRef<KhachSan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDanhGia", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaDanhGia
		{
			get
			{
				return this._MaDanhGia;
			}
			set
			{
				if ((this._MaDanhGia != value))
				{
					this.OnMaDanhGiaChanging(value);
					this.SendPropertyChanging();
					this._MaDanhGia = value;
					this.SendPropertyChanged("MaDanhGia");
					this.OnMaDanhGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemDanhGia", DbType="Decimal(2,1)")]
		public System.Nullable<decimal> DiemDanhGia
		{
			get
			{
				return this._DiemDanhGia;
			}
			set
			{
				if ((this._DiemDanhGia != value))
				{
					this.OnDiemDanhGiaChanging(value);
					this.SendPropertyChanging();
					this._DiemDanhGia = value;
					this.SendPropertyChanged("DiemDanhGia");
					this.OnDiemDanhGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThuocLoai", DbType="NVarChar(10)")]
		public string ThuocLoai
		{
			get
			{
				return this._ThuocLoai;
			}
			set
			{
				if ((this._ThuocLoai != value))
				{
					this.OnThuocLoaiChanging(value);
					this.SendPropertyChanging();
					this._ThuocLoai = value;
					this.SendPropertyChanged("ThuocLoai");
					this.OnThuocLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhachSan", DbType="Int")]
		public System.Nullable<int> MaKhachSan
		{
			get
			{
				return this._MaKhachSan;
			}
			set
			{
				if ((this._MaKhachSan != value))
				{
					if (this._KhachSan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhachSanChanging(value);
					this.SendPropertyChanging();
					this._MaKhachSan = value;
					this.SendPropertyChanged("MaKhachSan");
					this.OnMaKhachSanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachSan_DanhGia", Storage="_KhachSan", ThisKey="MaKhachSan", OtherKey="MaKhachSan", IsForeignKey=true)]
		public KhachSan KhachSan
		{
			get
			{
				return this._KhachSan.Entity;
			}
			set
			{
				KhachSan previousValue = this._KhachSan.Entity;
				if (((previousValue != value) 
							|| (this._KhachSan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachSan.Entity = null;
						previousValue.DanhGias.Remove(this);
					}
					this._KhachSan.Entity = value;
					if ((value != null))
					{
						value.DanhGias.Add(this);
						this._MaKhachSan = value.MaKhachSan;
					}
					else
					{
						this._MaKhachSan = default(Nullable<int>);
					}
					this.SendPropertyChanged("KhachSan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DiaDiem")]
	public partial class DiaDiem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDiaDiem;
		
		private string _TenDiaDiem;
		
		private EntitySet<KhachSan> _KhachSans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDiaDiemChanging(int value);
    partial void OnMaDiaDiemChanged();
    partial void OnTenDiaDiemChanging(string value);
    partial void OnTenDiaDiemChanged();
    #endregion
		
		public DiaDiem()
		{
			this._KhachSans = new EntitySet<KhachSan>(new Action<KhachSan>(this.attach_KhachSans), new Action<KhachSan>(this.detach_KhachSans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDiaDiem", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaDiaDiem
		{
			get
			{
				return this._MaDiaDiem;
			}
			set
			{
				if ((this._MaDiaDiem != value))
				{
					this.OnMaDiaDiemChanging(value);
					this.SendPropertyChanging();
					this._MaDiaDiem = value;
					this.SendPropertyChanged("MaDiaDiem");
					this.OnMaDiaDiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDiaDiem", DbType="NVarChar(50)")]
		public string TenDiaDiem
		{
			get
			{
				return this._TenDiaDiem;
			}
			set
			{
				if ((this._TenDiaDiem != value))
				{
					this.OnTenDiaDiemChanging(value);
					this.SendPropertyChanging();
					this._TenDiaDiem = value;
					this.SendPropertyChanged("TenDiaDiem");
					this.OnTenDiaDiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DiaDiem_KhachSan", Storage="_KhachSans", ThisKey="MaDiaDiem", OtherKey="MaDiaDiem")]
		public EntitySet<KhachSan> KhachSans
		{
			get
			{
				return this._KhachSans;
			}
			set
			{
				this._KhachSans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KhachSans(KhachSan entity)
		{
			this.SendPropertyChanging();
			entity.DiaDiem = this;
		}
		
		private void detach_KhachSans(KhachSan entity)
		{
			this.SendPropertyChanging();
			entity.DiaDiem = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DichVu")]
	public partial class DichVu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDichVu;
		
		private string _Ten;
		
		private string _ThongTin;
		
		private EntitySet<CT_DichVu> _CT_DichVus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDichVuChanging(int value);
    partial void OnMaDichVuChanged();
    partial void OnTenChanging(string value);
    partial void OnTenChanged();
    partial void OnThongTinChanging(string value);
    partial void OnThongTinChanged();
    #endregion
		
		public DichVu()
		{
			this._CT_DichVus = new EntitySet<CT_DichVu>(new Action<CT_DichVu>(this.attach_CT_DichVus), new Action<CT_DichVu>(this.detach_CT_DichVus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDichVu", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaDichVu
		{
			get
			{
				return this._MaDichVu;
			}
			set
			{
				if ((this._MaDichVu != value))
				{
					this.OnMaDichVuChanging(value);
					this.SendPropertyChanging();
					this._MaDichVu = value;
					this.SendPropertyChanged("MaDichVu");
					this.OnMaDichVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(50)")]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this.OnTenChanging(value);
					this.SendPropertyChanging();
					this._Ten = value;
					this.SendPropertyChanged("Ten");
					this.OnTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThongTin", DbType="NVarChar(100)")]
		public string ThongTin
		{
			get
			{
				return this._ThongTin;
			}
			set
			{
				if ((this._ThongTin != value))
				{
					this.OnThongTinChanging(value);
					this.SendPropertyChanging();
					this._ThongTin = value;
					this.SendPropertyChanged("ThongTin");
					this.OnThongTinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DichVu_CT_DichVu", Storage="_CT_DichVus", ThisKey="MaDichVu", OtherKey="MaDichVu")]
		public EntitySet<CT_DichVu> CT_DichVus
		{
			get
			{
				return this._CT_DichVus;
			}
			set
			{
				this._CT_DichVus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CT_DichVus(CT_DichVu entity)
		{
			this.SendPropertyChanging();
			entity.DichVu = this;
		}
		
		private void detach_CT_DichVus(CT_DichVu entity)
		{
			this.SendPropertyChanging();
			entity.DichVu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DonDatPhong")]
	public partial class DonDatPhong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDonDatPhong;
		
		private System.Nullable<System.DateTime> _NgayNhanPhong;
		
		private System.Nullable<System.DateTime> _NgayTraPhong;
		
		private System.Nullable<int> _MaKhachHang;
		
		private EntitySet<ChiTiet_DonDatPhong> _ChiTiet_DonDatPhongs;
		
		private EntityRef<KhachHang> _KhachHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDonDatPhongChanging(int value);
    partial void OnMaDonDatPhongChanged();
    partial void OnNgayNhanPhongChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayNhanPhongChanged();
    partial void OnNgayTraPhongChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayTraPhongChanged();
    partial void OnMaKhachHangChanging(System.Nullable<int> value);
    partial void OnMaKhachHangChanged();
    #endregion
		
		public DonDatPhong()
		{
			this._ChiTiet_DonDatPhongs = new EntitySet<ChiTiet_DonDatPhong>(new Action<ChiTiet_DonDatPhong>(this.attach_ChiTiet_DonDatPhongs), new Action<ChiTiet_DonDatPhong>(this.detach_ChiTiet_DonDatPhongs));
			this._KhachHang = default(EntityRef<KhachHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDonDatPhong", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaDonDatPhong
		{
			get
			{
				return this._MaDonDatPhong;
			}
			set
			{
				if ((this._MaDonDatPhong != value))
				{
					this.OnMaDonDatPhongChanging(value);
					this.SendPropertyChanging();
					this._MaDonDatPhong = value;
					this.SendPropertyChanged("MaDonDatPhong");
					this.OnMaDonDatPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayNhanPhong", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayNhanPhong
		{
			get
			{
				return this._NgayNhanPhong;
			}
			set
			{
				if ((this._NgayNhanPhong != value))
				{
					this.OnNgayNhanPhongChanging(value);
					this.SendPropertyChanging();
					this._NgayNhanPhong = value;
					this.SendPropertyChanged("NgayNhanPhong");
					this.OnNgayNhanPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTraPhong", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayTraPhong
		{
			get
			{
				return this._NgayTraPhong;
			}
			set
			{
				if ((this._NgayTraPhong != value))
				{
					this.OnNgayTraPhongChanging(value);
					this.SendPropertyChanging();
					this._NgayTraPhong = value;
					this.SendPropertyChanged("NgayTraPhong");
					this.OnNgayTraPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhachHang", DbType="Int")]
		public System.Nullable<int> MaKhachHang
		{
			get
			{
				return this._MaKhachHang;
			}
			set
			{
				if ((this._MaKhachHang != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhachHangChanging(value);
					this.SendPropertyChanging();
					this._MaKhachHang = value;
					this.SendPropertyChanged("MaKhachHang");
					this.OnMaKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DonDatPhong_ChiTiet_DonDatPhong", Storage="_ChiTiet_DonDatPhongs", ThisKey="MaDonDatPhong", OtherKey="MaDonDatPhong")]
		public EntitySet<ChiTiet_DonDatPhong> ChiTiet_DonDatPhongs
		{
			get
			{
				return this._ChiTiet_DonDatPhongs;
			}
			set
			{
				this._ChiTiet_DonDatPhongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_DonDatPhong", Storage="_KhachHang", ThisKey="MaKhachHang", OtherKey="MaKhachHang", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.DonDatPhongs.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.DonDatPhongs.Add(this);
						this._MaKhachHang = value.MaKhachHang;
					}
					else
					{
						this._MaKhachHang = default(Nullable<int>);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTiet_DonDatPhongs(ChiTiet_DonDatPhong entity)
		{
			this.SendPropertyChanging();
			entity.DonDatPhong = this;
		}
		
		private void detach_ChiTiet_DonDatPhongs(ChiTiet_DonDatPhong entity)
		{
			this.SendPropertyChanging();
			entity.DonDatPhong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HinhAnh")]
	public partial class HinhAnh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaHinhAnh;
		
		private System.Nullable<int> _MaKhachSan;
		
		private string _HinhAnh1;
		
		private EntityRef<KhachSan> _KhachSan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHinhAnhChanging(int value);
    partial void OnMaHinhAnhChanged();
    partial void OnMaKhachSanChanging(System.Nullable<int> value);
    partial void OnMaKhachSanChanged();
    partial void OnHinhAnh1Changing(string value);
    partial void OnHinhAnh1Changed();
    #endregion
		
		public HinhAnh()
		{
			this._KhachSan = default(EntityRef<KhachSan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHinhAnh", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaHinhAnh
		{
			get
			{
				return this._MaHinhAnh;
			}
			set
			{
				if ((this._MaHinhAnh != value))
				{
					this.OnMaHinhAnhChanging(value);
					this.SendPropertyChanging();
					this._MaHinhAnh = value;
					this.SendPropertyChanged("MaHinhAnh");
					this.OnMaHinhAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhachSan", DbType="Int")]
		public System.Nullable<int> MaKhachSan
		{
			get
			{
				return this._MaKhachSan;
			}
			set
			{
				if ((this._MaKhachSan != value))
				{
					if (this._KhachSan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhachSanChanging(value);
					this.SendPropertyChanging();
					this._MaKhachSan = value;
					this.SendPropertyChanged("MaKhachSan");
					this.OnMaKhachSanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="HinhAnh", Storage="_HinhAnh1", DbType="VarChar(50)")]
		public string HinhAnh1
		{
			get
			{
				return this._HinhAnh1;
			}
			set
			{
				if ((this._HinhAnh1 != value))
				{
					this.OnHinhAnh1Changing(value);
					this.SendPropertyChanging();
					this._HinhAnh1 = value;
					this.SendPropertyChanged("HinhAnh1");
					this.OnHinhAnh1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachSan_HinhAnh", Storage="_KhachSan", ThisKey="MaKhachSan", OtherKey="MaKhachSan", IsForeignKey=true)]
		public KhachSan KhachSan
		{
			get
			{
				return this._KhachSan.Entity;
			}
			set
			{
				KhachSan previousValue = this._KhachSan.Entity;
				if (((previousValue != value) 
							|| (this._KhachSan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachSan.Entity = null;
						previousValue.HinhAnhs.Remove(this);
					}
					this._KhachSan.Entity = value;
					if ((value != null))
					{
						value.HinhAnhs.Add(this);
						this._MaKhachSan = value.MaKhachSan;
					}
					else
					{
						this._MaKhachSan = default(Nullable<int>);
					}
					this.SendPropertyChanged("KhachSan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachHang")]
	public partial class KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaKhachHang;
		
		private string _TenKhachHang;
		
		private string _DiaChi;
		
		private string _DienThoai;
		
		private EntitySet<DonDatPhong> _DonDatPhongs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKhachHangChanging(int value);
    partial void OnMaKhachHangChanged();
    partial void OnTenKhachHangChanging(string value);
    partial void OnTenKhachHangChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnDienThoaiChanging(string value);
    partial void OnDienThoaiChanged();
    #endregion
		
		public KhachHang()
		{
			this._DonDatPhongs = new EntitySet<DonDatPhong>(new Action<DonDatPhong>(this.attach_DonDatPhongs), new Action<DonDatPhong>(this.detach_DonDatPhongs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhachHang", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaKhachHang
		{
			get
			{
				return this._MaKhachHang;
			}
			set
			{
				if ((this._MaKhachHang != value))
				{
					this.OnMaKhachHangChanging(value);
					this.SendPropertyChanging();
					this._MaKhachHang = value;
					this.SendPropertyChanged("MaKhachHang");
					this.OnMaKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKhachHang", DbType="NVarChar(50)")]
		public string TenKhachHang
		{
			get
			{
				return this._TenKhachHang;
			}
			set
			{
				if ((this._TenKhachHang != value))
				{
					this.OnTenKhachHangChanging(value);
					this.SendPropertyChanging();
					this._TenKhachHang = value;
					this.SendPropertyChanged("TenKhachHang");
					this.OnTenKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(100)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="VarChar(50)")]
		public string DienThoai
		{
			get
			{
				return this._DienThoai;
			}
			set
			{
				if ((this._DienThoai != value))
				{
					this.OnDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._DienThoai = value;
					this.SendPropertyChanged("DienThoai");
					this.OnDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_DonDatPhong", Storage="_DonDatPhongs", ThisKey="MaKhachHang", OtherKey="MaKhachHang")]
		public EntitySet<DonDatPhong> DonDatPhongs
		{
			get
			{
				return this._DonDatPhongs;
			}
			set
			{
				this._DonDatPhongs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DonDatPhongs(DonDatPhong entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_DonDatPhongs(DonDatPhong entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachSan")]
	public partial class KhachSan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaKhachSan;
		
		private System.Nullable<int> _MaDiaDiem;
		
		private string _TenKhachSan;
		
		private string _DiaChi;
		
		private string _ThongTin;
		
		private string _Video;
		
		private string _AnhBia;
		
		private EntitySet<ChinhSach> _ChinhSaches;
		
		private EntitySet<ChiTiet_LoaiPhong> _ChiTiet_LoaiPhongs;
		
		private EntitySet<CT_DichVu> _CT_DichVus;
		
		private EntitySet<CT_TienIch> _CT_TienIches;
		
		private EntitySet<DanhGia> _DanhGias;
		
		private EntitySet<HinhAnh> _HinhAnhs;
		
		private EntityRef<DiaDiem> _DiaDiem;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKhachSanChanging(int value);
    partial void OnMaKhachSanChanged();
    partial void OnMaDiaDiemChanging(System.Nullable<int> value);
    partial void OnMaDiaDiemChanged();
    partial void OnTenKhachSanChanging(string value);
    partial void OnTenKhachSanChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnThongTinChanging(string value);
    partial void OnThongTinChanged();
    partial void OnVideoChanging(string value);
    partial void OnVideoChanged();
    partial void OnAnhBiaChanging(string value);
    partial void OnAnhBiaChanged();
    #endregion
		
		public KhachSan()
		{
			this._ChinhSaches = new EntitySet<ChinhSach>(new Action<ChinhSach>(this.attach_ChinhSaches), new Action<ChinhSach>(this.detach_ChinhSaches));
			this._ChiTiet_LoaiPhongs = new EntitySet<ChiTiet_LoaiPhong>(new Action<ChiTiet_LoaiPhong>(this.attach_ChiTiet_LoaiPhongs), new Action<ChiTiet_LoaiPhong>(this.detach_ChiTiet_LoaiPhongs));
			this._CT_DichVus = new EntitySet<CT_DichVu>(new Action<CT_DichVu>(this.attach_CT_DichVus), new Action<CT_DichVu>(this.detach_CT_DichVus));
			this._CT_TienIches = new EntitySet<CT_TienIch>(new Action<CT_TienIch>(this.attach_CT_TienIches), new Action<CT_TienIch>(this.detach_CT_TienIches));
			this._DanhGias = new EntitySet<DanhGia>(new Action<DanhGia>(this.attach_DanhGias), new Action<DanhGia>(this.detach_DanhGias));
			this._HinhAnhs = new EntitySet<HinhAnh>(new Action<HinhAnh>(this.attach_HinhAnhs), new Action<HinhAnh>(this.detach_HinhAnhs));
			this._DiaDiem = default(EntityRef<DiaDiem>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhachSan", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaKhachSan
		{
			get
			{
				return this._MaKhachSan;
			}
			set
			{
				if ((this._MaKhachSan != value))
				{
					this.OnMaKhachSanChanging(value);
					this.SendPropertyChanging();
					this._MaKhachSan = value;
					this.SendPropertyChanged("MaKhachSan");
					this.OnMaKhachSanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDiaDiem", DbType="Int")]
		public System.Nullable<int> MaDiaDiem
		{
			get
			{
				return this._MaDiaDiem;
			}
			set
			{
				if ((this._MaDiaDiem != value))
				{
					if (this._DiaDiem.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDiaDiemChanging(value);
					this.SendPropertyChanging();
					this._MaDiaDiem = value;
					this.SendPropertyChanged("MaDiaDiem");
					this.OnMaDiaDiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKhachSan", DbType="NVarChar(50)")]
		public string TenKhachSan
		{
			get
			{
				return this._TenKhachSan;
			}
			set
			{
				if ((this._TenKhachSan != value))
				{
					this.OnTenKhachSanChanging(value);
					this.SendPropertyChanging();
					this._TenKhachSan = value;
					this.SendPropertyChanged("TenKhachSan");
					this.OnTenKhachSanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(100)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThongTin", DbType="NVarChar(1000)")]
		public string ThongTin
		{
			get
			{
				return this._ThongTin;
			}
			set
			{
				if ((this._ThongTin != value))
				{
					this.OnThongTinChanging(value);
					this.SendPropertyChanging();
					this._ThongTin = value;
					this.SendPropertyChanged("ThongTin");
					this.OnThongTinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Video", DbType="VarChar(100)")]
		public string Video
		{
			get
			{
				return this._Video;
			}
			set
			{
				if ((this._Video != value))
				{
					this.OnVideoChanging(value);
					this.SendPropertyChanging();
					this._Video = value;
					this.SendPropertyChanged("Video");
					this.OnVideoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnhBia", DbType="VarChar(50)")]
		public string AnhBia
		{
			get
			{
				return this._AnhBia;
			}
			set
			{
				if ((this._AnhBia != value))
				{
					this.OnAnhBiaChanging(value);
					this.SendPropertyChanging();
					this._AnhBia = value;
					this.SendPropertyChanged("AnhBia");
					this.OnAnhBiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachSan_ChinhSach", Storage="_ChinhSaches", ThisKey="MaKhachSan", OtherKey="MaKhachSan")]
		public EntitySet<ChinhSach> ChinhSaches
		{
			get
			{
				return this._ChinhSaches;
			}
			set
			{
				this._ChinhSaches.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachSan_ChiTiet_LoaiPhong", Storage="_ChiTiet_LoaiPhongs", ThisKey="MaKhachSan", OtherKey="MaKhachSan")]
		public EntitySet<ChiTiet_LoaiPhong> ChiTiet_LoaiPhongs
		{
			get
			{
				return this._ChiTiet_LoaiPhongs;
			}
			set
			{
				this._ChiTiet_LoaiPhongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachSan_CT_DichVu", Storage="_CT_DichVus", ThisKey="MaKhachSan", OtherKey="MaKhachSan")]
		public EntitySet<CT_DichVu> CT_DichVus
		{
			get
			{
				return this._CT_DichVus;
			}
			set
			{
				this._CT_DichVus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachSan_CT_TienIch", Storage="_CT_TienIches", ThisKey="MaKhachSan", OtherKey="MaKhachSan")]
		public EntitySet<CT_TienIch> CT_TienIches
		{
			get
			{
				return this._CT_TienIches;
			}
			set
			{
				this._CT_TienIches.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachSan_DanhGia", Storage="_DanhGias", ThisKey="MaKhachSan", OtherKey="MaKhachSan")]
		public EntitySet<DanhGia> DanhGias
		{
			get
			{
				return this._DanhGias;
			}
			set
			{
				this._DanhGias.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachSan_HinhAnh", Storage="_HinhAnhs", ThisKey="MaKhachSan", OtherKey="MaKhachSan")]
		public EntitySet<HinhAnh> HinhAnhs
		{
			get
			{
				return this._HinhAnhs;
			}
			set
			{
				this._HinhAnhs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DiaDiem_KhachSan", Storage="_DiaDiem", ThisKey="MaDiaDiem", OtherKey="MaDiaDiem", IsForeignKey=true)]
		public DiaDiem DiaDiem
		{
			get
			{
				return this._DiaDiem.Entity;
			}
			set
			{
				DiaDiem previousValue = this._DiaDiem.Entity;
				if (((previousValue != value) 
							|| (this._DiaDiem.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DiaDiem.Entity = null;
						previousValue.KhachSans.Remove(this);
					}
					this._DiaDiem.Entity = value;
					if ((value != null))
					{
						value.KhachSans.Add(this);
						this._MaDiaDiem = value.MaDiaDiem;
					}
					else
					{
						this._MaDiaDiem = default(Nullable<int>);
					}
					this.SendPropertyChanged("DiaDiem");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChinhSaches(ChinhSach entity)
		{
			this.SendPropertyChanging();
			entity.KhachSan = this;
		}
		
		private void detach_ChinhSaches(ChinhSach entity)
		{
			this.SendPropertyChanging();
			entity.KhachSan = null;
		}
		
		private void attach_ChiTiet_LoaiPhongs(ChiTiet_LoaiPhong entity)
		{
			this.SendPropertyChanging();
			entity.KhachSan = this;
		}
		
		private void detach_ChiTiet_LoaiPhongs(ChiTiet_LoaiPhong entity)
		{
			this.SendPropertyChanging();
			entity.KhachSan = null;
		}
		
		private void attach_CT_DichVus(CT_DichVu entity)
		{
			this.SendPropertyChanging();
			entity.KhachSan = this;
		}
		
		private void detach_CT_DichVus(CT_DichVu entity)
		{
			this.SendPropertyChanging();
			entity.KhachSan = null;
		}
		
		private void attach_CT_TienIches(CT_TienIch entity)
		{
			this.SendPropertyChanging();
			entity.KhachSan = this;
		}
		
		private void detach_CT_TienIches(CT_TienIch entity)
		{
			this.SendPropertyChanging();
			entity.KhachSan = null;
		}
		
		private void attach_DanhGias(DanhGia entity)
		{
			this.SendPropertyChanging();
			entity.KhachSan = this;
		}
		
		private void detach_DanhGias(DanhGia entity)
		{
			this.SendPropertyChanging();
			entity.KhachSan = null;
		}
		
		private void attach_HinhAnhs(HinhAnh entity)
		{
			this.SendPropertyChanging();
			entity.KhachSan = this;
		}
		
		private void detach_HinhAnhs(HinhAnh entity)
		{
			this.SendPropertyChanging();
			entity.KhachSan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LienHe")]
	public partial class LienHe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaLienHe;
		
		private string _TenKhachHang;
		
		private string _Email;
		
		private string _ThongTinLienHe;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLienHeChanging(int value);
    partial void OnMaLienHeChanged();
    partial void OnTenKhachHangChanging(string value);
    partial void OnTenKhachHangChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnThongTinLienHeChanging(string value);
    partial void OnThongTinLienHeChanged();
    #endregion
		
		public LienHe()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLienHe", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaLienHe
		{
			get
			{
				return this._MaLienHe;
			}
			set
			{
				if ((this._MaLienHe != value))
				{
					this.OnMaLienHeChanging(value);
					this.SendPropertyChanging();
					this._MaLienHe = value;
					this.SendPropertyChanged("MaLienHe");
					this.OnMaLienHeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKhachHang", DbType="NVarChar(30)")]
		public string TenKhachHang
		{
			get
			{
				return this._TenKhachHang;
			}
			set
			{
				if ((this._TenKhachHang != value))
				{
					this.OnTenKhachHangChanging(value);
					this.SendPropertyChanging();
					this._TenKhachHang = value;
					this.SendPropertyChanged("TenKhachHang");
					this.OnTenKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThongTinLienHe", DbType="NVarChar(200)")]
		public string ThongTinLienHe
		{
			get
			{
				return this._ThongTinLienHe;
			}
			set
			{
				if ((this._ThongTinLienHe != value))
				{
					this.OnThongTinLienHeChanging(value);
					this.SendPropertyChanging();
					this._ThongTinLienHe = value;
					this.SendPropertyChanged("ThongTinLienHe");
					this.OnThongTinLienHeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiPhong")]
	public partial class LoaiPhong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaLoaiPhong;
		
		private string _TenLoaiPhong;
		
		private string _ThongTin;
		
		private EntitySet<ChiTiet_LoaiPhong> _ChiTiet_LoaiPhongs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiPhongChanging(int value);
    partial void OnMaLoaiPhongChanged();
    partial void OnTenLoaiPhongChanging(string value);
    partial void OnTenLoaiPhongChanged();
    partial void OnThongTinChanging(string value);
    partial void OnThongTinChanged();
    #endregion
		
		public LoaiPhong()
		{
			this._ChiTiet_LoaiPhongs = new EntitySet<ChiTiet_LoaiPhong>(new Action<ChiTiet_LoaiPhong>(this.attach_ChiTiet_LoaiPhongs), new Action<ChiTiet_LoaiPhong>(this.detach_ChiTiet_LoaiPhongs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiPhong", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaLoaiPhong
		{
			get
			{
				return this._MaLoaiPhong;
			}
			set
			{
				if ((this._MaLoaiPhong != value))
				{
					this.OnMaLoaiPhongChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiPhong = value;
					this.SendPropertyChanged("MaLoaiPhong");
					this.OnMaLoaiPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoaiPhong", DbType="NVarChar(50)")]
		public string TenLoaiPhong
		{
			get
			{
				return this._TenLoaiPhong;
			}
			set
			{
				if ((this._TenLoaiPhong != value))
				{
					this.OnTenLoaiPhongChanging(value);
					this.SendPropertyChanging();
					this._TenLoaiPhong = value;
					this.SendPropertyChanged("TenLoaiPhong");
					this.OnTenLoaiPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThongTin", DbType="NVarChar(500)")]
		public string ThongTin
		{
			get
			{
				return this._ThongTin;
			}
			set
			{
				if ((this._ThongTin != value))
				{
					this.OnThongTinChanging(value);
					this.SendPropertyChanging();
					this._ThongTin = value;
					this.SendPropertyChanged("ThongTin");
					this.OnThongTinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiPhong_ChiTiet_LoaiPhong", Storage="_ChiTiet_LoaiPhongs", ThisKey="MaLoaiPhong", OtherKey="MaLoaiPhong")]
		public EntitySet<ChiTiet_LoaiPhong> ChiTiet_LoaiPhongs
		{
			get
			{
				return this._ChiTiet_LoaiPhongs;
			}
			set
			{
				this._ChiTiet_LoaiPhongs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTiet_LoaiPhongs(ChiTiet_LoaiPhong entity)
		{
			this.SendPropertyChanging();
			entity.LoaiPhong = this;
		}
		
		private void detach_ChiTiet_LoaiPhongs(ChiTiet_LoaiPhong entity)
		{
			this.SendPropertyChanging();
			entity.LoaiPhong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QuanTri")]
	public partial class QuanTri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaQuanTri;
		
		private string _Username_QT;
		
		private string _Password_QT;
		
		private string _Email_QT;
		
		private System.Nullable<int> _MaQuyen;
		
		private EntityRef<QuyenHan> _QuyenHan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaQuanTriChanging(int value);
    partial void OnMaQuanTriChanged();
    partial void OnUsername_QTChanging(string value);
    partial void OnUsername_QTChanged();
    partial void OnPassword_QTChanging(string value);
    partial void OnPassword_QTChanged();
    partial void OnEmail_QTChanging(string value);
    partial void OnEmail_QTChanged();
    partial void OnMaQuyenChanging(System.Nullable<int> value);
    partial void OnMaQuyenChanged();
    #endregion
		
		public QuanTri()
		{
			this._QuyenHan = default(EntityRef<QuyenHan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaQuanTri", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaQuanTri
		{
			get
			{
				return this._MaQuanTri;
			}
			set
			{
				if ((this._MaQuanTri != value))
				{
					this.OnMaQuanTriChanging(value);
					this.SendPropertyChanging();
					this._MaQuanTri = value;
					this.SendPropertyChanged("MaQuanTri");
					this.OnMaQuanTriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username_QT", DbType="VarChar(30)")]
		public string Username_QT
		{
			get
			{
				return this._Username_QT;
			}
			set
			{
				if ((this._Username_QT != value))
				{
					this.OnUsername_QTChanging(value);
					this.SendPropertyChanging();
					this._Username_QT = value;
					this.SendPropertyChanged("Username_QT");
					this.OnUsername_QTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password_QT", DbType="VarChar(30)")]
		public string Password_QT
		{
			get
			{
				return this._Password_QT;
			}
			set
			{
				if ((this._Password_QT != value))
				{
					this.OnPassword_QTChanging(value);
					this.SendPropertyChanging();
					this._Password_QT = value;
					this.SendPropertyChanged("Password_QT");
					this.OnPassword_QTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email_QT", DbType="VarChar(30)")]
		public string Email_QT
		{
			get
			{
				return this._Email_QT;
			}
			set
			{
				if ((this._Email_QT != value))
				{
					this.OnEmail_QTChanging(value);
					this.SendPropertyChanging();
					this._Email_QT = value;
					this.SendPropertyChanged("Email_QT");
					this.OnEmail_QTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaQuyen", DbType="Int")]
		public System.Nullable<int> MaQuyen
		{
			get
			{
				return this._MaQuyen;
			}
			set
			{
				if ((this._MaQuyen != value))
				{
					if (this._QuyenHan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaQuyenChanging(value);
					this.SendPropertyChanging();
					this._MaQuyen = value;
					this.SendPropertyChanged("MaQuyen");
					this.OnMaQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QuyenHan_QuanTri", Storage="_QuyenHan", ThisKey="MaQuyen", OtherKey="MaQuyen", IsForeignKey=true)]
		public QuyenHan QuyenHan
		{
			get
			{
				return this._QuyenHan.Entity;
			}
			set
			{
				QuyenHan previousValue = this._QuyenHan.Entity;
				if (((previousValue != value) 
							|| (this._QuyenHan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QuyenHan.Entity = null;
						previousValue.QuanTris.Remove(this);
					}
					this._QuyenHan.Entity = value;
					if ((value != null))
					{
						value.QuanTris.Add(this);
						this._MaQuyen = value.MaQuyen;
					}
					else
					{
						this._MaQuyen = default(Nullable<int>);
					}
					this.SendPropertyChanged("QuyenHan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QuyenHan")]
	public partial class QuyenHan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaQuyen;
		
		private string _TenQuyen;
		
		private EntitySet<QuanTri> _QuanTris;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaQuyenChanging(int value);
    partial void OnMaQuyenChanged();
    partial void OnTenQuyenChanging(string value);
    partial void OnTenQuyenChanged();
    #endregion
		
		public QuyenHan()
		{
			this._QuanTris = new EntitySet<QuanTri>(new Action<QuanTri>(this.attach_QuanTris), new Action<QuanTri>(this.detach_QuanTris));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaQuyen", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaQuyen
		{
			get
			{
				return this._MaQuyen;
			}
			set
			{
				if ((this._MaQuyen != value))
				{
					this.OnMaQuyenChanging(value);
					this.SendPropertyChanging();
					this._MaQuyen = value;
					this.SendPropertyChanged("MaQuyen");
					this.OnMaQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenQuyen", DbType="NVarChar(30)")]
		public string TenQuyen
		{
			get
			{
				return this._TenQuyen;
			}
			set
			{
				if ((this._TenQuyen != value))
				{
					this.OnTenQuyenChanging(value);
					this.SendPropertyChanging();
					this._TenQuyen = value;
					this.SendPropertyChanged("TenQuyen");
					this.OnTenQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QuyenHan_QuanTri", Storage="_QuanTris", ThisKey="MaQuyen", OtherKey="MaQuyen")]
		public EntitySet<QuanTri> QuanTris
		{
			get
			{
				return this._QuanTris;
			}
			set
			{
				this._QuanTris.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_QuanTris(QuanTri entity)
		{
			this.SendPropertyChanging();
			entity.QuyenHan = this;
		}
		
		private void detach_QuanTris(QuanTri entity)
		{
			this.SendPropertyChanging();
			entity.QuyenHan = null;
		}
	}
}
#pragma warning restore 1591
